blog/blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :about  
  resources :posts do
    resources :comments
  end
  
  root "posts#index"

end

blog/blog/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

blog/blog/app/models/post.rb
class Post < ActiveRecord::Base
		has_many :comments, dependent: :destroy
		validates :title, presence: true, length: { minimum: 5 }
		validates :body, presence: true
end

blog/blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blog/blog/app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

blog/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to @post
	end

end

blog/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end	

	def create
		@post = Post.new(post_params)

		if @post.save
		redirect_to @post
		else
		render 'new'
			end 
		end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	private 
		def post_params 
			params.require(:post).permit(:title, :body)
		end
end

blog/blog/app/helpers/about_helper.rb
module AboutHelper
end

blog/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/blog/app/views/about/index.html.erb
	<h1>Hello, Welcome to Code Innovator's Blog</h1>

	<p>Hello, My name is Thoams Kim. I was getting interested in Computer Programming when I was in a thrid year of university.</p>	

blog/blog/app/views/about/show.html.erb
	<h1>Hello, Welcome to Code Innovator's Blog/h1>

	<p>Hello, My name is Thoams Kim. I was getting interested in Computer Programming when I was in a thrid year of university.</p>	

blog/blog/app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_item"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

	<% if user_signed_in? %>
	<p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button",data: { confirm: 'Are you sure'} %>
	</p>
	<% end %>
	</div>

blog/blog/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
	<%= f.label :name %><br>
	<%= f.text_field :name %>
</p>

<p>
	<%= f.label :body %><br>
	<%= f.text_area :body %>
</p>
<br>
<p>
	<%= f.submit %>
</p>
<% end %>

blog/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="main_content">
  <div id="header">
    <div id="logo">
      <%= link_to root_path do %>
      <%= image_tag "logo.jpg" %>
      <% end %>
    </div>
 
     <a><%= link_to "blog", root_path %></a>
     <a><%= link_to "about", about_index_path %></a>
     <a>Email</a>
     <a>Twitter</a>
     <a>Instagrams</a>
     <a><%= link_to "Github", "https://github.com/CodeInnovator"%></a>

  <% if !user_signed_in? %>
  <div id="admin_log">
   <p class="sign_in"><%= link_to "Admin Log In", new_user_session_path %></p>
   </div>
   <% end %>
</div>

<% if current_page?(root_path) %>
    <h1 style="color:brown">All Posts</h1>
    <% elsif current_page?(about_index_path) %>
    <p>About</p>
    <% else %>
    <%= link_to "Back to All Posts", root_path %>
    <% end %>
      <% if user_signed_in? %>
    <div class="buttons">
    <button class="button"><%= link_to "New Post", new_post_path %></button>
    <button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
    </div>
    <% end %>
 </div>


  <% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert") %>
  <% end %>

  <%= yield %>
</div>




</body>
</html>

blog/blog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
			<ul>
			<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<p>
	<%= f.label :title %> <br>
	<%= f.text_field :title %><br>
	</p>
	<p>
	<%= f.label :body %> <br>
	<%= f.text_area :body %><br>
	</p>
	<p><%= f.submit %></p>
	<% end %>

blog/blog/app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>
	<%= render 'form' %>
</div>

blog/blog/app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post_wrapper">
	<h2 class="title"><%= link_to post.title, post %></h2>
	<p class="date"><%= post.created_at.strftime("%B, %D, %Y") %></p>
	</div>
	<% end %>

blog/blog/app/views/posts/new.html.erb
<div id="page_wrapper">
<h1>New Post</h1>

<%= render 'form' %>

</div>

blog/blog/app/views/posts/show.html.erb
<div id="post_content">
<h1 class="title">
<%= @post.title %>
</h1>

<p class="date">
 submitted <%= time_ago_in_words(@post.created_at) %> ago
 <% if user_signed_in? %>
| <%= link_to 'Edit', edit_post_path(@post) %>
| <%= link_to 'Delete', post_path(@post), method: :delete, data:{ confirm: 'Are you sure?'} %>
	<% end %>
 </p>
 <p class="body">
 	<%= @post.body %>
 </p>

 <div id="comments">
 	<h2><%= @post.comments.count %> Comments </h2>
 	<%= render @post.comments %>

 	<h3>Add a comment:</h3>
 	<%= render "comments/form" %>
 </div>
	
 </div>